# Generated by Django 3.2.4 on 2021-08-17 12:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='profile_pics')),
                ('hotel_name', models.CharField(max_length=150)),
                ('hotel_address', models.TextField()),
                ('mobile_number', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message="Entered mobile number isn't in a right format!", regex='^[0-9]{10,15}$')])),
                ('gst_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Enter Valid GSt Number', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')])),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.IntegerField(unique=True)),
                ('IFC_number', models.CharField(max_length=10, unique=True)),
                ('branch_name', models.CharField(max_length=50)),
                ('company_pan', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Company not valid', regex='^[A-Za-z]{5}\\d{4}[A-Za-z]{1}$')])),
                ('user_linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
