export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAIL = 'PROFILE_FAIL';

export const GET_PRODUCT = 'GET_PRODUCT'
export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const DELETE_PRODUCT= 'DELETE_PRODUCT'
export const UPDATE_PROUCT= 'UPDATE_PROUCT'

export const GET_SUPPLIER = 'GET_SUPPLIER'
export const CREATE_SUPPLIER = 'CREATE_SUPPLIER'
export const DELETE_SUPPLIER= 'DELETE_SUPPLIER'
export const UPDATE_SUPPLIER= 'UPDATE_SUPPLIER'

export const GET_PURCHASE = 'GET_PURCHASE'
export const CREATE_PURCHASE = 'CREATE_PURCHASE'
export const DELETE_PURCHASE= 'DELETE_PURCHASE'
export const UPDATE_PURCHASE= 'UPDATE_PURCHASE'

export const GET_FLOORINV= 'GET_FLOORINV'

export const GET_ORDER= 'GET_ORDER'

export const GET_RETAIL_DASHBOARD= 'GET_RETAIL_DASHBOARD'
export const GET_FLOOR_DASHBOARD= 'GET_FLOOR_DASHBOARD'

export const BASE_URL = 'http://192.168.0.179:8000/'