# Generated by Django 3.2.4 on 2021-12-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0003_alter_product_user_linked'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('edible', 'Edible'), ('non-edible', 'Non-Edible')], default='edible', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='product_weight_category',
            field=models.CharField(choices=[('kilogram', 'Kilogram'), ('gram', 'Gram'), ('litre', 'Litre'), ('ml', 'Mili Litre'), ('pieces', 'Pieces')], default='kilogram', max_length=10),
        ),
    ]
