# Generated by Django 3.2.4 on 2021-12-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0004_auto_20211211_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_weight_per_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
