# Generated by Django 3.2.4 on 2022-02-17 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant_inventory_api', '0010_alter_inventoryorder_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill_of_material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('production_cost', models.FloatField()),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('receipe', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Bill_of_material_Kitchen_Inventory_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityUsed', models.FloatField()),
                ('bomAssociated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_of_material.bill_of_material')),
            ],
        ),
        migrations.CreateModel(
            name='Bill_of_material_Floor_Inventory_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityUsed', models.FloatField()),
                ('bomAssociated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill_of_material.bill_of_material')),
                ('itemAssociated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_inventory_api.floorinventory')),
            ],
        ),
    ]
