# Generated by Django 3.2.4 on 2022-02-17 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bill_of_material', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_of_material_kitchen_inventory_item',
            name='kitchenitemAssociated',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bill_of_material_Item', to='bill_of_material.bill_of_material'),
            preserve_default=False,
        ),
    ]
