# Generated by Django 3.2.4 on 2021-10-24 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant_inventory_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorinventory',
            name='user_linked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floorinventory', to=settings.AUTH_USER_MODEL),
        ),
    ]
