# Generated by Django 3.2.4 on 2021-10-24 20:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant_inventory_api', '0002_alter_floorinventory_user_linked'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField()),
                ('delievery_date', models.DateField(default=datetime.datetime(2021, 10, 24, 20, 46, 59, 691405, tzinfo=utc))),
                ('user_linked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
