# Generated by Django 3.2.4 on 2021-10-24 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0003_alter_product_user_linked'),
        ('restaurant_inventory_api', '0004_alter_inventoryorder_delievery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryorder',
            name='order_name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InventoryOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_inventory_api.inventoryorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_api.product')),
            ],
        ),
    ]
