# Generated by Django 3.2.4 on 2021-10-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_inventory_api', '0005_auto_20211025_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryorder',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryorder',
            name='remark',
            field=models.TextField(blank=True, default=None),
        ),
    ]
