# Generated by Django 3.2.4 on 2021-10-28 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0003_alter_product_user_linked'),
        ('restaurant_inventory_api', '0006_auto_20211025_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryorderitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='restaurant_inventory_api.inventoryorder'),
        ),
        migrations.AlterField(
            model_name='inventoryorderitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product_api.product'),
        ),
    ]
