# Generated by Django 3.2.4 on 2021-10-29 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_inventory_api', '0008_inventoryorder_issued_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryOrderNewItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('product_quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_orders', to='restaurant_inventory_api.inventoryorder')),
            ],
        ),
    ]
