# Generated by Django 3.2.4 on 2021-10-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_inventory_api', '0009_inventoryordernewitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryorder',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
