# Generated by Django 3.2.4 on 2021-09-20 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='gst_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter Valid GSt Number', regex='^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$')]),
        ),
    ]
