# Generated by Django 3.2.4 on 2021-10-14 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier_api', '0002_alter_supplier_gst_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllinStatePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invNumber', models.CharField(max_length=50)),
                ('total_amount', models.IntegerField(default=0)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_api.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AllOutStatePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invNumber', models.CharField(max_length=50)),
                ('total_amount', models.IntegerField(default=0)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_api.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutStatePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('product_price', models.IntegerField(default=0)),
                ('product_gst', models.CharField(choices=[('5%', '5%'), ('12%', '12%'), ('18%', '18%'), ('28%', '28%')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('outstateInv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases_api.alloutstatepurchase')),
            ],
        ),
        migrations.CreateModel(
            name='inStatePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
                ('product_price', models.IntegerField(default=0)),
                ('product_cgst', models.CharField(choices=[('5%', '5%'), ('12%', '12%'), ('18%', '18%'), ('28%', '28%')], max_length=10)),
                ('product_sgst', models.CharField(choices=[('5%', '5%'), ('12%', '12%'), ('18%', '18%'), ('28%', '28%')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('instateInv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases_api.allinstatepurchase')),
            ],
        ),
    ]
